services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    restart: always
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
  frontend:
    image: redpencil/frontend-timekeeper:0.8.1
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.26.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
  kimai-sync:
    image: redpencil/timekeeper-kimai-sync-service:0.3.0
    environment:
      API_TOKEN: "your_secret_kimai_api_token_here"
      KIMAI_ENDPOINT: "https://test.kimai.redpencil.io/api"
      DEFAULT_MU_AUTH_SCOPE: "http://services.redpencil.io/timekeeper-kimai-sync-service"
    restart: always
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    restart: always
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.14
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    restart: always
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.3.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    labels:
      - "logging=true"
  login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    labels:
      - "logging=true"
  registration:
    image: semtech/mu-registration-service:2.8.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    labels:
      - "logging=true"
