PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX people: <http://timekeeper.redpencil.io/people/>
PREFIX accounts: <http://timekeeper.redpencil.io/accounts/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX account: <http://mu.semte.ch/vocabularies/account/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
   GRAPH <http://mu.semte.ch/graphs/users> {
     people:43b12fdc-f75b-4180-bd13-35371e2ba643 a foaf:Person ;
                   foaf:name "Kobe Mertens" ;
                   foaf:account accounts:0f7a9af5-ed38-4556-b1b5-b1f15ef565a0 ;
                   mu:uuid "43b12fdc-f75b-4180-bd13-35371e2ba643" ;
                   dcterms:created "2024-11-28T12:58:13+00:00"^^xsd:dateTime ;
                   dcterms:modified "2024-11-28T12:58:13+00:00"^^xsd:dateTime .
     accounts:0f7a9af5-ed38-4556-b1b5-b1f15ef565a0 a foaf:OnlineAccount ;
                   foaf:accountName "kobe.mertens@redpencil.io" ;
                   mu:uuid "0f7a9af5-ed38-4556-b1b5-b1f15ef565a0" ;
                   account:password """$2a$12$SXYxxKJIRqELcJoU2ZsQC.XUo6aqN1NpKMlN3dK5qA74Kx7Y.IDxa""" ;
                   account:salt "c2c5ef2cfe465ddbf03529176c2270ad" ;
                   account:status <http://mu.semte.ch/vocabularies/account/status/active> ;
                   dcterms:created "2024-11-28T12:58:13+00:00"^^xsd:dateTime ;
                   dcterms:modified "2024-11-28T12:58:13+00:00"^^xsd:dateTime .
    }
}