PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ical: <http://www.w3.org/2002/12/cal/ical#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX wf: <http://www.w3.org/2005/01/wf/flow#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX tempo: <http://purl.org/tempo/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/holidays> {
    ?publicHolidayInWeekendCounterUri 
      a qudt:Quantity ;
      mu:uuid ?publicHolidayInWeekendCounterUuid ;
      qudt:value "PT16H" ;
      prov:wasAssociatedWith ?employee ;
      qudt:hasQuantityKind <http://timekeeper.redpencil.io/concepts/eb9813ca-cfe5-444b-94b9-09874982d92c> ;
      tempo:validFrom "2025-01-01"^^xsd:date ;
      tempo:validTill "2026-01-01"^^xsd:date .
    ?advCounterUri 
      a qudt:Quantity ;
      mu:uuid ?advCounterUuid ;
      qudt:value "PT96H" ;
      prov:wasAssociatedWith ?employee ;
      qudt:hasQuantityKind <http://timekeeper.redpencil.io/concepts/80e059db-c653-49b6-b9e7-1ca0c03db47b> ;
      tempo:validFrom "2025-01-01"^^xsd:date ;
      tempo:validTill "2026-01-01"^^xsd:date .
    ?holidayCounterUri 
      a qudt:Quantity ;
      mu:uuid ?holidayCounterUuid ;
      qudt:value "PT160H" ;
      prov:wasAssociatedWith ?employee ;
      qudt:hasQuantityKind <http://timekeeper.redpencil.io/concepts/5608072c-3396-4ecc-9573-eee910179c1c> ;
      tempo:validFrom "2025-01-01"^^xsd:date ;
      tempo:validTill "2026-01-01"^^xsd:date .
    ?transferredHolidayCounterUri 
      a qudt:Quantity ;
      mu:uuid ?transferredHolidayCounterUuid ;
      qudt:value "PT0H" ;
      prov:wasAssociatedWith ?employee ;
      qudt:hasQuantityKind <http://timekeeper.redpencil.io/concepts/5dfc278c-d0f3-4978-9853-67c8a8379a58> ;
      tempo:validFrom "2025-01-01"^^xsd:date ;
      tempo:validTill "2026-01-01"^^xsd:date .
    ?overtimeCounterUri 
      a qudt:Quantity ;
      mu:uuid ?overtimeCounterUuid ;
      qudt:value "PT0H" ;
      prov:wasAssociatedWith ?employee ;
      qudt:hasQuantityKind <http://timekeeper.redpencil.io/concepts/5416871e-8bd7-473e-a101-1fc163f0e81e> ;
      tempo:validFrom "2025-01-01"^^xsd:date ;
      tempo:validTill "2026-01-01"^^xsd:date .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/users> {
    ?employee 
      a foaf:Person .
      <http://mu.semte.ch/user-groups/employee> foaf:member ?employee .
  }

  BIND(LCASE(STRUUID()) as ?publicHolidayInWeekendCounterUuid) .
  BIND(LCASE(STRUUID()) as ?advCounterUuid) .
  BIND(LCASE(STRUUID()) as ?holidayCounterUuid) .
  BIND(LCASE(STRUUID()) as ?transferredHolidayCounterUuid) .
  BIND(LCASE(STRUUID()) as ?overtimeCounterUuid) .

  BIND(URI(CONCAT("http://timekeeper.redpencil.io/holiday-counters/",?publicHolidayInWeekendCounterUuid)) as ?publicHolidayInWeekendCounterUri) .
  BIND(URI(CONCAT("http://timekeeper.redpencil.io/holiday-counters/",?advCounterUuid)) as ?advCounterUri) .
  BIND(URI(CONCAT("http://timekeeper.redpencil.io/holiday-counters/",?holidayCounterUuid)) as ?holidayCounterUri) .
  BIND(URI(CONCAT("http://timekeeper.redpencil.io/holiday-counters/",?transferredHolidayCounterUuid)) as ?transferredHolidayCounterUri) .
  BIND(URI(CONCAT("http://timekeeper.redpencil.io/holiday-counters/",?overtimeCounterUuid)) as ?overtimeCounterUri) .
}